// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"
import uuid "github.com/google/uuid"

// BoardOfDirectorsAdapter is an autogenerated mock type for the BoardOfDirectorsAdapter type
type BoardOfDirectorsAdapter struct {
	mock.Mock
}

// Search provides a mock function with given fields: profileID
func (_m *BoardOfDirectorsAdapter) Search(profileID uuid.UUID) ([]entity.Director, error) {
	ret := _m.Called(profileID)

	var r0 []entity.Director
	if rf, ok := ret.Get(0).(func(uuid.UUID) []entity.Director); ok {
		r0 = rf(profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Director)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
