// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// BureauService is an autogenerated mock type for the BureauService type
type BureauService struct {
	mock.Mock
}

// GetBureauStatus provides a mock function with given fields: person
func (_m *BureauService) GetBureauStatus(person entity.Person) (*entity.EnrichedInformation, error) {
	ret := _m.Called(person)

	var r0 *entity.EnrichedInformation
	if rf, ok := ret.Get(0).(func(entity.Person) *entity.EnrichedInformation); ok {
		r0 = rf(person)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.EnrichedInformation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.Person) error); ok {
		r1 = rf(person)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
