// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// CompliancePersonProcessor is an autogenerated mock type for the CompliancePersonProcessor type
type CompliancePersonProcessor struct {
	mock.Mock
}

// ExecuteForPerson provides a mock function with given fields: person, offer
func (_m *CompliancePersonProcessor) ExecuteForPerson(person entity.Person, offer string) (*entity.State, error) {
	ret := _m.Called(person, offer)

	var r0 *entity.State
	if rf, ok := ret.Get(0).(func(entity.Person, string) *entity.State); ok {
		r0 = rf(person, offer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.State)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.Person, string) error); ok {
		r1 = rf(person, offer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
