// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"
import uuid "github.com/google/uuid"

// ComplianceCommandPublisher is an autogenerated mock type for the ComplianceCommandPublisher type
type ComplianceCommandPublisher struct {
	mock.Mock
}

// SendCommand provides a mock function with given fields: entityID, parentID, engineName
func (_m *ComplianceCommandPublisher) SendCommand(entityID uuid.UUID, parentID *uuid.UUID, engineName string) (*entity.State, error) {
	ret := _m.Called(entityID, parentID, engineName)

	var r0 *entity.State
	if rf, ok := ret.Get(0).(func(uuid.UUID, *uuid.UUID, string) *entity.State); ok {
		r0 = rf(entityID, parentID, engineName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.State)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID, *uuid.UUID, string) error); ok {
		r1 = rf(entityID, parentID, engineName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
