// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// ContractRulesFactory is an autogenerated mock type for the ContractRulesFactory type
type ContractRulesFactory struct {
	mock.Mock
}

// GetRules provides a mock function with given fields: contract
func (_m *ContractRulesFactory) GetRules(contract entity.Contract) []entity.Rule {
	ret := _m.Called(contract)

	var r0 []entity.Rule
	if rf, ok := ret.Get(0).(func(entity.Contract) []entity.Rule); ok {
		r0 = rf(contract)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Rule)
		}
	}

	return r0
}
