// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"
import uuid "github.com/google/uuid"

// ContractRepository is an autogenerated mock type for the ContractRepository type
type ContractRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *ContractRepository) Get(id uuid.UUID) (*entity.Contract, error) {
	ret := _m.Called(id)

	var r0 *entity.Contract
	if rf, ok := ret.Get(0).(func(uuid.UUID) *entity.Contract); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Contract)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: contract
func (_m *ContractRepository) Save(contract entity.Contract) (*entity.Contract, error) {
	ret := _m.Called(contract)

	var r0 *entity.Contract
	if rf, ok := ret.Get(0).(func(entity.Contract) *entity.Contract); ok {
		r0 = rf(contract)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Contract)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.Contract) error); ok {
		r1 = rf(contract)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
