// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	"bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ContactService is an autogenerated mock type for the ContactService type
type ContactService struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *ContactService) Get(id uuid.UUID) (*entity.Contact, error) {
	ret := _m.Called(id)

	var r0 *entity.Contact
	if rf, ok := ret.Get(0).(func(uuid.UUID) *entity.Contact); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Contact)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
