// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import uuid "github.com/google/uuid"
import values "bitbucket.org/bexstech/temis-compliance/src/core/domain/values"

// EngineSelector is an autogenerated mock type for the EngineSelector type
type EngineSelector struct {
	mock.Mock
}

// GetEngineNameAndEntityId provides a mock function with given fields: event
func (_m *EngineSelector) GetEngineNameAndEntityId(event values.Event) (string, *uuid.UUID, error) {
	ret := _m.Called(event)

	var r0 string
	if rf, ok := ret.Get(0).(func(values.Event) string); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 *uuid.UUID
	if rf, ok := ret.Get(1).(func(values.Event) *uuid.UUID); ok {
		r1 = rf(event)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*uuid.UUID)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(values.Event) error); ok {
		r2 = rf(event)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
