// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// EnricherAdapter is an autogenerated mock type for the EnricherAdapter type
type EnricherAdapter struct {
	mock.Mock
}

// GetEnrichedPerson provides a mock function with given fields: documentNumber, profileID, personType, offerType, partnerID, roleTye
func (_m *EnricherAdapter) GetEnrichedPerson(documentNumber string, profileID string, personType string, offerType string, partnerID string, roleTye string) (*entity.EnrichedInformation, error) {
	ret := _m.Called(documentNumber, profileID, personType, offerType, partnerID, roleTye)

	var r0 *entity.EnrichedInformation
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, string) *entity.EnrichedInformation); ok {
		r0 = rf(documentNumber, profileID, personType, offerType, partnerID, roleTye)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.EnrichedInformation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string, string, string) error); ok {
		r1 = rf(documentNumber, profileID, personType, offerType, partnerID, roleTye)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
