// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import values "bitbucket.org/bexstech/temis-compliance/src/core/domain/values"

// EventTranslator is an autogenerated mock type for the EventTranslator type
type EventTranslator struct {
	mock.Mock
}

// Translate provides a mock function with given fields: message
func (_m *EventTranslator) Translate(message []byte) (*values.Event, error) {
	ret := _m.Called(message)

	var r0 *values.Event
	if rf, ok := ret.Get(0).(func([]byte) *values.Event); ok {
		r0 = rf(message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*values.Event)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
