// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import uuid "github.com/google/uuid"

// FileAdapter is an autogenerated mock type for the FileAdapter type
type FileAdapter struct {
	mock.Mock
}

// GetUrl provides a mock function with given fields: fileID
func (_m *FileAdapter) GetUrl(fileID uuid.UUID) (string, error) {
	ret := _m.Called(fileID)

	var r0 string
	if rf, ok := ret.Get(0).(func(uuid.UUID) string); ok {
		r0 = rf(fileID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(fileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
