// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// ForeignAccountAdapter is an autogenerated mock type for the ForeignAccountAdapter type
type ForeignAccountAdapter struct {
	mock.Mock
}

// Get provides a mock function with given fields: foreignAccountID
func (_m *ForeignAccountAdapter) Get(foreignAccountID string) (*entity.ForeignAccount, error) {
	ret := _m.Called(foreignAccountID)

	var r0 *entity.ForeignAccount
	if rf, ok := ret.Get(0).(func(string) *entity.ForeignAccount); ok {
		r0 = rf(foreignAccountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ForeignAccount)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(foreignAccountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
