// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// LimitPublisher is an autogenerated mock type for the LimitPublisher type
type LimitPublisher struct {
	mock.Mock
}

// Send provides a mock function with given fields: profile, state
func (_m *LimitPublisher) Send(profile entity.Profile, state entity.State) error {
	ret := _m.Called(profile, state)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Profile, entity.State) error); ok {
		r0 = rf(profile, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
