// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import values "bitbucket.org/bexstech/temis-compliance/src/core/domain/values"

// LockRepository is an autogenerated mock type for the LockRepository type
type LockRepository struct {
	mock.Mock
}

// BeginTransaction provides a mock function with given fields: event, processor
func (_m *LockRepository) BeginTransaction(event values.Event, processor func(values.Event, *bool) error) error {
	ret := _m.Called(event, processor)

	var r0 error
	if rf, ok := ret.Get(0).(func(values.Event, func(values.Event, *bool) error) error); ok {
		r0 = rf(event, processor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
