// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import _interfaces "bitbucket.org/bexstech/temis-compliance/src/core/_interfaces"
import mock "github.com/stretchr/testify/mock"

// MessageProcessor is an autogenerated mock type for the MessageProcessor type
type MessageProcessor struct {
	mock.Mock
}

// Process provides a mock function with given fields: message
func (_m *MessageProcessor) Process(message _interfaces.Message) (string, error) {
	ret := _m.Called(message)

	var r0 string
	if rf, ok := ret.Get(0).(func(_interfaces.Message) string); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(_interfaces.Message) error); ok {
		r1 = rf(message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
