// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import time "time"

// MetricsGenerator is an autogenerated mock type for the MetricsGenerator type
type MetricsGenerator struct {
	mock.Mock
}

// EventProcessed provides a mock function with given fields: handshake, result, requestReceived
func (_m *MetricsGenerator) EventProcessed(handshake string, result string, requestReceived time.Time) {
	_m.Called(handshake, result, requestReceived)
}

// EventReceived provides a mock function with given fields: publishedTime
func (_m *MetricsGenerator) EventReceived(publishedTime time.Time) {
	_m.Called(publishedTime)
}
