// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// NotificationRecipientAdapter is an autogenerated mock type for the NotificationRecipientAdapter type
type NotificationRecipientAdapter struct {
	mock.Mock
}

// Search provides a mock function with given fields: profileID
func (_m *NotificationRecipientAdapter) Search(profileID string) ([]entity.NotificationRecipient, error) {
	ret := _m.Called(profileID)

	var r0 []entity.NotificationRecipient
	if rf, ok := ret.Get(0).(func(string) []entity.NotificationRecipient); ok {
		r0 = rf(profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.NotificationRecipient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
