// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	"bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NotificationRecipientService is an autogenerated mock type for the NotificationRecipientService type
type NotificationRecipientService struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *NotificationRecipientService) Get(id string) (*entity.NotificationRecipient, error) {
	ret := _m.Called(id)

	var r0 *entity.NotificationRecipient
	if rf, ok := ret.Get(0).(func(string) *entity.NotificationRecipient); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.NotificationRecipient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: profileID
func (_m *NotificationRecipientService) Search(profileID string) ([]entity.NotificationRecipient, error) {
	ret := _m.Called(profileID)

	var r0 []entity.NotificationRecipient
	if rf, ok := ret.Get(0).(func(string) []entity.NotificationRecipient); ok {
		r0 = rf(profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.NotificationRecipient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
