// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"
import uuid "github.com/google/uuid"
import values "bitbucket.org/bexstech/temis-compliance/src/core/domain/values"

// OverrideRepository is an autogenerated mock type for the OverrideRepository type
type OverrideRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: entityID, set, name
func (_m *OverrideRepository) Delete(entityID uuid.UUID, set values.RuleSet, name values.RuleName) error {
	ret := _m.Called(entityID, set, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, values.RuleSet, values.RuleName) error); ok {
		r0 = rf(entityID, set, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByEntityID provides a mock function with given fields: entityID
func (_m *OverrideRepository) FindByEntityID(entityID uuid.UUID) (entity.Overrides, error) {
	ret := _m.Called(entityID)

	var r0 entity.Overrides
	if rf, ok := ret.Get(0).(func(uuid.UUID) entity.Overrides); ok {
		r0 = rf(entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entity.Overrides)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: override
func (_m *OverrideRepository) Save(override entity.Override) error {
	ret := _m.Called(override)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Override) error); ok {
		r0 = rf(override)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
