// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// OwnershipStructureAdapter is an autogenerated mock type for the OwnershipStructureAdapter type
type OwnershipStructureAdapter struct {
	mock.Mock
}

// Get provides a mock function with given fields: id, offerType, partnerID
func (_m *OwnershipStructureAdapter) Get(id string, offerType string, partnerID string) (*entity.OwnershipStructure, error) {
	ret := _m.Called(id, offerType, partnerID)

	var r0 *entity.OwnershipStructure
	if rf, ok := ret.Get(0).(func(string, string, string) *entity.OwnershipStructure); ok {
		r0 = rf(id, offerType, partnerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.OwnershipStructure)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(id, offerType, partnerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
