// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// PersonFactory is an autogenerated mock type for the PersonFactory type
type PersonFactory struct {
	mock.Mock
}

// Build provides a mock function with given fields: person
func (_m *PersonFactory) Build(person entity.Person) (*entity.Person, error) {
	ret := _m.Called(person)

	var r0 *entity.Person
	if rf, ok := ret.Get(0).(func(entity.Person) *entity.Person); ok {
		r0 = rf(person)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Person)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.Person) error); ok {
		r1 = rf(person)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
