// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// PersonRulesFactory is an autogenerated mock type for the PersonRulesFactory type
type PersonRulesFactory struct {
	mock.Mock
}

// GetRules provides a mock function with given fields: ruleSetConfig, person
func (_m *PersonRulesFactory) GetRules(ruleSetConfig entity.RuleSetConfig, person entity.Person) []entity.Rule {
	ret := _m.Called(ruleSetConfig, person)

	var r0 []entity.Rule
	if rf, ok := ret.Get(0).(func(entity.RuleSetConfig, entity.Person) []entity.Rule); ok {
		r0 = rf(ruleSetConfig, person)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Rule)
		}
	}

	return r0
}
