// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// PersonConstructor is an autogenerated mock type for the PersonConstructor type
type PersonConstructor struct {
	mock.Mock
}

// Assemble provides a mock function with given fields: person
func (_m *PersonConstructor) Assemble(person *entity.PersonWrapper) error {
	ret := _m.Called(person)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.PersonWrapper) error); ok {
		r0 = rf(person)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
