// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// ProfileConstructor is an autogenerated mock type for the ProfileConstructor type
type ProfileConstructor struct {
	mock.Mock
}

// Assemble provides a mock function with given fields: profile
func (_m *ProfileConstructor) Assemble(profile *entity.ProfileWrapper) error {
	ret := _m.Called(profile)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.ProfileWrapper) error); ok {
		r0 = rf(profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
