// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"
import uuid "github.com/google/uuid"

// QuestionFormAdapter is an autogenerated mock type for the QuestionFormAdapter type
type QuestionFormAdapter struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *QuestionFormAdapter) Get(id uuid.UUID) (*entity.QuestionForm, error) {
	ret := _m.Called(id)

	var r0 *entity.QuestionForm
	if rf, ok := ret.Get(0).(func(uuid.UUID) *entity.QuestionForm); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.QuestionForm)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
