// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
	"bitbucket.org/bexstech/temis-compliance/src/core/domain/values"
)
import mock "github.com/stretchr/testify/mock"

// Rule is an autogenerated mock type for the Rule type
type Rule struct {
	mock.Mock
}

// Analyze provides a mock function with given fields:
func (_m *Rule) Analyze() ([]entity.RuleResultV2, error) {
	ret := _m.Called()

	var r0 []entity.RuleResultV2
	if rf, ok := ret.Get(0).(func() []entity.RuleResultV2); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.RuleResultV2)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Name provides a mock function with given fields:
func (_m *Rule) Name() values.RuleSet {
	ret := _m.Called()

	var r0 values.RuleSet
	if rf, ok := ret.Get(0).(func() values.RuleSet); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(values.RuleSet)
	}

	return r0
}
