// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import _interfaces "bitbucket.org/bexstech/temis-compliance/src/core/_interfaces"
import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"
import uuid "github.com/google/uuid"

// RuleValidator is an autogenerated mock type for the RuleValidator type
type RuleValidator struct {
	mock.Mock
}

// NewInstance provides a mock function with given fields:
func (_m *RuleValidator) NewInstance() _interfaces.RuleValidator {
	ret := _m.Called()

	var r0 _interfaces.RuleValidator
	if rf, ok := ret.Get(0).(func() _interfaces.RuleValidator); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(_interfaces.RuleValidator)
		}
	}

	return r0
}

// SetRules provides a mock function with given fields: rules
func (_m *RuleValidator) SetRules(rules []entity.RuleValidatorStep) {
	_m.Called(rules)
}

// Validate provides a mock function with given fields: state, override, noCache, entityID, engineName
func (_m *RuleValidator) Validate(state entity.State, override entity.Overrides, noCache bool, entityID uuid.UUID, engineName string) (*entity.State, error) {
	ret := _m.Called(state, override, noCache, entityID, engineName)

	var r0 *entity.State
	if rf, ok := ret.Get(0).(func(entity.State, entity.Overrides, bool, uuid.UUID, string) *entity.State); ok {
		r0 = rf(state, override, noCache, entityID, engineName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.State)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.State, entity.Overrides, bool, uuid.UUID, string) error); ok {
		r1 = rf(state, override, noCache, entityID, engineName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
