// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// ShareholdingAnalyzer is an autogenerated mock type for the ShareholdingAnalyzer type
type ShareholdingAnalyzer struct {
	mock.Mock
}

// Analyze provides a mock function with given fields:
func (_m *ShareholdingAnalyzer) Analyze() (*entity.RuleResultV2, *entity.OwnershipStructure, error) {
	ret := _m.Called()

	var r0 *entity.RuleResultV2
	if rf, ok := ret.Get(0).(func() *entity.RuleResultV2); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RuleResultV2)
		}
	}

	var r1 *entity.OwnershipStructure
	if rf, ok := ret.Get(1).(func() *entity.OwnershipStructure); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entity.OwnershipStructure)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
