// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// ShareholdersAnalyzer is an autogenerated mock type for the ShareholdersAnalyzer type
type ShareholdersAnalyzer struct {
	mock.Mock
}

// Analyze provides a mock function with given fields: ownershipStructure
func (_m *ShareholdersAnalyzer) Analyze(ownershipStructure entity.OwnershipStructure) (*entity.RuleResultV2, error) {
	ret := _m.Called(ownershipStructure)

	var r0 *entity.RuleResultV2
	if rf, ok := ret.Get(0).(func(entity.OwnershipStructure) *entity.RuleResultV2); ok {
		r0 = rf(ownershipStructure)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RuleResultV2)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.OwnershipStructure) error); ok {
		r1 = rf(ownershipStructure)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
