// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// StateMachine is an autogenerated mock type for the StateMachine type
type StateMachine struct {
	mock.Mock
}

// CalculateState provides a mock function with given fields: state
func (_m *StateMachine) CalculateState(state entity.State) *entity.State {
	ret := _m.Called(state)

	var r0 *entity.State
	if rf, ok := ret.Get(0).(func(entity.State) *entity.State); ok {
		r0 = rf(state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.State)
		}
	}

	return r0
}
