// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import _interfaces "bitbucket.org/bexstech/temis-compliance/src/core/_interfaces"
import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"
import uuid "github.com/google/uuid"

// SubEngine is an autogenerated mock type for the SubEngine type
type SubEngine struct {
	mock.Mock
}

// GetName provides a mock function with given fields:
func (_m *SubEngine) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewInstance provides a mock function with given fields:
func (_m *SubEngine) NewInstance() _interfaces.SubEngine {
	ret := _m.Called()

	var r0 _interfaces.SubEngine
	if rf, ok := ret.Get(0).(func() _interfaces.SubEngine); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(_interfaces.SubEngine)
		}
	}

	return r0
}

// PosProcessing provides a mock function with given fields: previousState, newState, entityID
func (_m *SubEngine) PosProcessing(previousState *entity.State, newState *entity.State, entityID uuid.UUID) error {
	ret := _m.Called(previousState, newState, entityID)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.State, *entity.State, uuid.UUID) error); ok {
		r0 = rf(previousState, newState, entityID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Prepare provides a mock function with given fields: person, offerType
func (_m *SubEngine) Prepare(person entity.Person, offerType string) error {
	ret := _m.Called(person, offerType)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Person, string) error); ok {
		r0 = rf(person, offerType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Validate provides a mock function with given fields: state, override, noCache, entityID, engineName
func (_m *SubEngine) Validate(state entity.State, override entity.Overrides, noCache bool, entityID uuid.UUID, engineName string) (*entity.State, error) {
	ret := _m.Called(state, override, noCache, entityID, engineName)

	var r0 *entity.State
	if rf, ok := ret.Get(0).(func(entity.State, entity.Overrides, bool, uuid.UUID, string) *entity.State); ok {
		r0 = rf(state, override, noCache, entityID, engineName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.State)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.State, entity.Overrides, bool, uuid.UUID, string) error); ok {
		r1 = rf(state, override, noCache, entityID, engineName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
