// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// TemisConfigAdapter is an autogenerated mock type for the TemisConfigAdapter type
type TemisConfigAdapter struct {
	mock.Mock
}

// GetCadastralValidationConfig provides a mock function with given fields: ctx, personType, roleType, offerType, partnerID
func (_m *TemisConfigAdapter) GetCadastralValidationConfig(ctx context.Context, personType string, roleType string, offerType string, partnerID string) (*entity.CadastralValidationConfig, error) {
	ret := _m.Called(ctx, personType, roleType, offerType, partnerID)

	var r0 *entity.CadastralValidationConfig
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *entity.CadastralValidationConfig); ok {
		r0 = rf(ctx, personType, roleType, offerType, partnerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CadastralValidationConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, personType, roleType, offerType, partnerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
