// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "bitbucket.org/bexstech/temis-compliance/src/core/domain/entity"
import mock "github.com/stretchr/testify/mock"

// TreeAdapterPublisher is an autogenerated mock type for the TreeAdapterPublisher type
type TreeAdapterPublisher struct {
	mock.Mock
}

// Send provides a mock function with given fields: profile, accounts, addresses
func (_m *TreeAdapterPublisher) Send(profile entity.Profile, accounts []entity.Account, addresses []entity.Address) error {
	ret := _m.Called(profile, accounts, addresses)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Profile, []entity.Account, []entity.Address) error); ok {
		r0 = rf(profile, accounts, addresses)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
